import pygame
from pystery import init, quit, load_image, Game, Scene, ImageEntity, RectRegion, Dir

class ExampleGame(Game):
    def __init__(self):
        super().__init__()

        ################################ 
        #SET UP YOUR GAME STARTING HERE#
        ################################

        pygame.mixer.init() 

        pygame.mixer.music.load('assets/audio/rain.mp3') 
        pygame.mixer.music.play(-1)
        
        typing_sound = self.load_sound('assets/audio/typing.mp3')

        text_scene1 = Scene(img='assets/bg/Text1.png')
        text_scene2 = Scene(img='assets/bg/Text2.png')
        text_scene3 = Scene(img='assets/bg/Text3.png')
        text_scene4 = Scene(img='assets/bg/Text4.png')
        text_scene5 = Scene(img='assets/bg/Text5.png')
        text_scene6 = Scene(img='assets/bg/Text6.png')
        text_scene7 = Scene(img='assets/bg/Text7.png')
        text_scene8 = Scene(img='assets/bg/Text8.png')
        text_scene9 = Scene(img='assets/bg/Text9.png')
        text_scene10 = Scene(img='assets/bg/Text10.png')
        text_scene11 = Scene(img='assets/bg/Text11.png')
        outside_scene = Scene(img='assets/bg/outside.png')
        living_room_scene = Scene(img='assets/bg/living_room.png')
        phone_scene = Scene(img='assets/bg/phone.png')
        computer_scene1 = Scene(img='assets/bg/computer_scene1.jpg')
        computer_scene2 = Scene(img='assets/bg/computer_scene2.jpg')
        dining_room_scene = Scene(img='assets/bg/dining_room.png')
        glass_scene = Scene(img='assets/bg/glass.jpeg')
        glass_removed_scene = Scene(img='assets/bg/glass_removed.jpeg')
        bedroom_scene = Scene(img='assets/bg/bedroom.jpg')
        journal_scene1 = Scene(img='assets/bg/journal_scene1.jpeg')
        journal_scene2 = Scene(img='assets/bg/journal_scene2.jpeg')
        attic_scene = Scene(img='assets/bg/attic.png')
        glove_scene = Scene(img='assets/bg/glove.jpg')
        glove_blood_scene = Scene(img='assets/bg/glove_blood.jpg')
        accusation_scene = Scene(img='assets/bg/accusation.png')
        win_scene = Scene(img='assets/bg/win.png')
        lose_scene = Scene(img='assets/bg/lose.png')

        def click_file():
            typing_sound.play()
            living_room_scene.remove_region(living_room_click_region1)
            living_room_click_region1.link_to_scene(computer_scene2)
            living_room_scene.add_region(living_room_click_region1)
            computer_scene2.add_dir_link(Dir.UP, living_room_scene)

        text_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region1.link_to_scene(text_scene2)
        text_scene1.add_region(text_click_region1)
        text_click_region2 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region2.link_to_scene(text_scene3)
        text_scene2.add_region(text_click_region2)
        text_click_region3 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region3.link_to_scene(text_scene4)
        text_scene3.add_region(text_click_region3)
        text_click_region4 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region4.link_to_scene(text_scene5)
        text_scene4.add_region(text_click_region4)
        text_click_region5 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region5.link_to_scene(text_scene6)
        text_scene5.add_region(text_click_region5)
        text_click_region6 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region6.link_to_scene(text_scene7)
        text_scene6.add_region(text_click_region6)
        text_scene7_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_scene7_click_region1.link_to_scene(text_scene8)
        text_scene7.add_region(text_scene7_click_region1)
        text_scene8_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_scene8_click_region1.link_to_scene(text_scene9)
        text_scene8.add_region(text_scene8_click_region1)
        text_scene9_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_scene9_click_region1.link_to_scene(text_scene10)
        text_scene9.add_region(text_scene9_click_region1)
        text_scene10_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_scene10_click_region1.link_to_scene(outside_scene)
        text_scene10.add_region(text_scene10_click_region1)
        outside_scene_click_region1 = RectRegion(left=675, top=450, width=150, height=150)
        outside_scene_click_region1.link_to_scene(living_room_scene)
        outside_scene.add_region(outside_scene_click_region1)
        living_room_click_region1 = RectRegion(left=680, top=370, width=120, height=70)
        living_room_click_region1.link_to_scene(computer_scene1)
        living_room_click_region2 = RectRegion(left= 550, top=390, width=60, height=70)
        living_room_click_region2.link_to_scene(phone_scene)
        living_room_scene.add_region(living_room_click_region2)
        living_room_scene.add_region(living_room_click_region1)
        living_room_scene.add_dir_link(Dir.RIGHT, dining_room_scene)
        phone_scene.add_dir_link(Dir.UP, living_room_scene)
        computer_scene1.add_dir_link(Dir.UP, living_room_scene)
        computer_scene1_click_region1 = RectRegion(left= 200, top=132, width=900, height=100)
        computer_scene1_click_region1.link_to_scene(computer_scene2)
        computer_scene1_click_region1.on_click(click_file)
        computer_scene1.add_region(computer_scene1_click_region1)
        computer_scene2.add_dir_link(Dir.UP, living_room_scene)
        dining_room_scene.add_dir_link(Dir.LEFT, living_room_scene)
        dining_room_scene.add_dir_link(Dir.RIGHT, bedroom_scene)
        dining_room_scene_click_region1 = RectRegion(left= 1050, top=570, width=90, height=60)
        dining_room_scene_click_region1.link_to_scene(glass_scene)
        dining_room_scene.add_region(dining_room_scene_click_region1)
        glass_scene.add_dir_link(Dir.UP, dining_room_scene)
        glass_scene_click_region1 = RectRegion(left= 0, top=0, width=1280, height=720)
        glass_scene_click_region1.link_to_scene(glass_removed_scene)
        glass_scene.add_region(glass_scene_click_region1)
        glass_scene.add_region(glass_scene_click_region1)
        glass_removed_scene.add_dir_link(Dir.UP, dining_room_scene)
        bedroom_scene.add_dir_link(Dir.LEFT, dining_room_scene)
        bedroom_scene.add_dir_link(Dir.RIGHT, attic_scene)
        bedroom_scene_click_region1 = RectRegion(left= 10, top=610, width=140, height=90)
        bedroom_scene_click_region1.link_to_scene(journal_scene1)
        bedroom_scene.add_region(bedroom_scene_click_region1)
        journal_scene1.add_dir_link(Dir.UP, bedroom_scene)
        journal_scene1_click_region1 = RectRegion(left= 650, top=130, width=250, height=200)
        journal_scene1_click_region1.link_to_scene(journal_scene2)
        journal_scene1.add_region(journal_scene1_click_region1)
        journal_scene2.add_dir_link(Dir.UP, bedroom_scene)
        journal_scene2.add_dir_link(Dir.LEFT, journal_scene1)
        attic_scene.add_dir_link(Dir.LEFT, bedroom_scene)
        attic_scene.add_dir_link(Dir.RIGHT, text_scene11)
        attic_scene_click_region1 = RectRegion(left= 1120, top=570, width=60, height=100)
        attic_scene_click_region1.link_to_scene(glove_scene)
        attic_scene.add_region(attic_scene_click_region1)
        glove_scene.add_dir_link(Dir.UP, attic_scene)
        glove_scene_click_region1 = RectRegion(left=830, top=290, width=200, height=150)
        glove_scene_click_region1.link_to_scene(glove_blood_scene)
        glove_scene.add_region(glove_scene_click_region1)
        glove_blood_scene.add_dir_link(Dir.UP, glove_scene)
        text_scene11.add_dir_link(Dir.LEFT, attic_scene)
        text_scene11.add_dir_link(Dir.RIGHT, accusation_scene)
        accusation_scene_click_region1 = RectRegion(left= 740, top=220, width=190, height=450)
        accusation_scene_click_region1.link_to_scene(win_scene)
        accusation_scene.add_region(accusation_scene_click_region1)
        accusation_scene_click_region2 = RectRegion(left= 200, top=200, width=200, height=500)
        accusation_scene_click_region2.link_to_scene(lose_scene)
        accusation_scene.add_region(accusation_scene_click_region2)
        accusation_scene_click_region3 = RectRegion(left= 935, top=440, width=200, height=210)
        accusation_scene_click_region3.link_to_scene(lose_scene)
        accusation_scene.add_region(accusation_scene_click_region3)
        accusation_scene_click_region4 = RectRegion(left= 600, top=220, width = 115, height=470)
        accusation_scene_click_region4.link_to_scene(lose_scene)
        accusation_scene.add_region(accusation_scene_click_region4)
        accusation_scene_click_region5 = RectRegion(left= 410, top=200, width=150, height=470)
        accusation_scene_click_region5.link_to_scene(lose_scene)
        accusation_scene.add_region(accusation_scene_click_region5)


        self.set_start_scene(text_scene1)
init()
while True:
    # run the game until quit or restart
    run_result = ExampleGame().run()


    # if run_result is False, the game should quit. otherwise, we loop and restart it
    if not run_result:
        break
quit()