import pygame
from pystery import init, quit, load_image, Game, Scene, ImageEntity, RectRegion, Dir

class ExampleGame(Game):
    def __init__(self):
        super().__init__()

        ################################ 
        #SET UP YOUR GAME STARTING HERE#
        ################################

        pygame.mixer.init() 

        pygame.mixer.music.load('assets/audio/rain.mp3') 
        pygame.mixer.music.play(-1)
        
        typing_sound = self.load_sound('assets/audio/typing.mp3')
        key_get = self.load_sound('assets/audio/key_get.mp3')
        locked_sound = self.load_sound('assets/audio/locked.mp3')

        text_scene1 = Scene(img='assets/bg/Text1.png')
        text_scene2 = Scene(img='assets/bg/Text2.png')
        text_scene3 = Scene(img='assets/bg/Text3.png')
        text_scene4 = Scene(img='assets/bg/Text4.png')
        text_scene5 = Scene(img='assets/bg/Text5.png')
        text_scene6 = Scene(img='assets/bg/Text6.png')
        text_scene7 = Scene(img='assets/bg/Text7.png')
        text_scene8 = Scene(img='assets/bg/Text8.png')
        text_scene9 = Scene(img='assets/bg/Text9.png')
        text_scene10 = Scene(img='assets/bg/Text10.png')
        text_scene11 = Scene(img='assets/bg/Text11.png')
        angela = Scene(img='assets/bg/angela.png')
        uncal_gregor = Scene(img='assets/bg/uncalgregor.png')
        twins = Scene(img='assets/bg/twins.png')
        amy = Scene(img='assets/bg/amy.png')
        nanny = Scene(img='assets/bg/nanny.png')
        alabies1 = Scene(img='assets/bg/alabies1.png')
        alabies2 = Scene(img='assets/bg/alabies2.png')
        alabies3 = Scene(img='assets/bg/alabies3.png')
        alabies4 = Scene(img='assets/bg/alabies4.png')
        alabies5 = Scene(img='assets/bg/alabies5.png')
        outside_scene = Scene(img='assets/bg/outside.png')
        living_room_scene = Scene(img='assets/bg/living_room.png')
        phone_scene = Scene(img='assets/bg/phone.png')
        computer_scene1 = Scene(img='assets/bg/computer_scene1.jpg')
        computer_scene2 = Scene(img='assets/bg/computer_scene2.jpg')
        dining_room_scene = Scene(img='assets/bg/dining_room.png')
        glass_scene = Scene(img='assets/bg/glass.jpeg')
        glass_removed_scene = Scene(img='assets/bg/glass_removed.jpeg')
        bedroom_scene = Scene(img='assets/bg/bedroom.jpg')
        journal_scene1 = Scene(img='assets/bg/journal_scene1.jpeg')
        journal_scene2 = Scene(img='assets/bg/journal_scene2.jpeg')
        attic_scene = Scene(img='assets/bg/attic.png')
        lockbox_scene = Scene(img='assets/bg/lockbox.png')
        box_scene = Scene(img='assets/bg/box.png')
        glove_scene = Scene(img='assets/bg/glove.jpg')
        glove_blood_scene = Scene(img='assets/bg/glove_blood.jpg')
        accusation_scene1 = Scene(img='assets/bg/accusation1.png')
        accusation_scene2 = Scene(img='assets/bg/accusation2.png')
        accusation_scene3 = Scene(img='assets/bg/accusation3.png')
        accusation_scene4 = Scene(img='assets/bg/accusation4.png')
        accusation_scene5 = Scene(img='assets/bg/accusation5.png')
        accusation_scene6 = Scene(img='assets/bg/accusation6.png')
        accusation_scene7 = Scene(img='assets/bg/accusation7.png')
        lose_scene = Scene(img='assets/bg/lose.png')
        final_scene = Scene(img='assets/bg/final.jpeg')
        win_scene1 = Scene(img='assets/bg/win1.png')
        win_scene2 = Scene(img='assets/bg/win2.png')
        win_scene3 = Scene(img='assets/bg/win3.png')
        win_scene4 = Scene(img='assets/bg/win4.png')
        win_scene5 = Scene(img='assets/bg/win5.png')
        win_scene6 = Scene(img='assets/bg/win6.png')
        win_scene7 = Scene(img='assets/bg/win7.png')
        win_scene8 = Scene(img='assets/bg/win8.png')
        win_scene9 = Scene(img='assets/bg/win9.png')
        win_scene10 = Scene(img='assets/bg/win10.png')
        win_scene11 = Scene(img='assets/bg/win11.png')
        win_scene12 = Scene(img='assets/bg/win12.png')
        win_scene13 = Scene(img='assets/bg/win13.png')
        win_scene14 = Scene(img='assets/bg/win14.png')


        def click_file():
            typing_sound.play()
            living_room_scene.remove_region(living_room_click_region1)
            living_room_click_region1.link_to_scene(computer_scene2)
            living_room_scene.add_region(living_room_click_region1)
            computer_scene2.add_dir_link(Dir.UP, living_room_scene)

        def click_key():
            key_get.play()
            dining_room_scene.remove_region(dining_room_scene_click_region2)
            dining_room_scene.add_dir_link(Dir.RIGHT, bedroom_scene)
        
        def click_glass():
            key_get.play()
            dining_room_scene.remove_region(dining_room_scene_click_region1)
        
        def click_box():
            if living_room_click_region1.linked_scene == computer_scene2:
                key_get.play()
                lockbox_scene_click_region1 = RectRegion(left= 620, top=400, width=150, height=100)
                lockbox_scene_click_region1.link_to_scene(box_scene)
                lockbox_scene.add_region(lockbox_scene_click_region1)
                attic_scene_click_region2.link_to_scene(box_scene)
                attic_scene.add_dir_link(Dir.RIGHT, text_scene11)
            else:
                locked_sound.play()
            

        text_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region1.link_to_scene(text_scene2)
        text_scene1.add_region(text_click_region1)
        text_click_region2 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region2.link_to_scene(text_scene3)
        text_scene2.add_region(text_click_region2)
        text_click_region3 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region3.link_to_scene(text_scene4)
        text_scene3.add_region(text_click_region3)
        text_click_region4 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region4.link_to_scene(text_scene5)
        text_scene4.add_region(text_click_region4)
        text_click_region5 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region5.link_to_scene(text_scene6)
        text_scene5.add_region(text_click_region5)
        text_click_region6 = RectRegion(left=0, top=0, width=1280, height=720)
        text_click_region6.link_to_scene(text_scene7)
        text_scene6.add_region(text_click_region6)
        text_scene7_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_scene7_click_region1.link_to_scene(text_scene8)
        text_scene7.add_region(text_scene7_click_region1)
        text_scene8_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_scene8_click_region1.link_to_scene(text_scene9)
        text_scene8.add_region(text_scene8_click_region1)
        text_scene9_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_scene9_click_region1.link_to_scene(text_scene10)
        text_scene9.add_region(text_scene9_click_region1)
        text_scene10_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        text_scene10_click_region1.link_to_scene(angela)
        text_scene10.add_region(text_scene10_click_region1)
        angela_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        angela_click_region1.link_to_scene(uncal_gregor)
        angela.add_region(angela_click_region1)
        uncal_gregor_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        uncal_gregor_click_region1.link_to_scene(twins)
        uncal_gregor.add_region(uncal_gregor_click_region1)
        twins_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        twins_click_region1.link_to_scene(amy)
        twins.add_region(twins_click_region1)
        amy_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        amy_click_region1.link_to_scene(nanny)
        amy.add_region(amy_click_region1)
        nanny_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        nanny_click_region1.link_to_scene(outside_scene)
        nanny.add_region(nanny_click_region1)
        outside_scene_click_region1 = RectRegion(left=675, top=450, width=150, height=150)
        outside_scene_click_region1.link_to_scene(alabies1)
        outside_scene.add_region(outside_scene_click_region1)
        alabies1_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        alabies1_click_region1.link_to_scene(alabies2)
        alabies1.add_region(alabies1_click_region1)
        alabies2_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        alabies2_click_region1.link_to_scene(alabies3)
        alabies2.add_region(alabies2_click_region1)
        alabies3_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        alabies3_click_region1.link_to_scene(alabies4)
        alabies3.add_region(alabies3_click_region1)
        alabies4_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        alabies4_click_region1.link_to_scene(alabies5)
        alabies4.add_region(alabies4_click_region1)
        alabies5_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        alabies5_click_region1.link_to_scene(living_room_scene)
        alabies5.add_region(alabies5_click_region1)
        living_room_click_region1 = RectRegion(left=680, top=370, width=120, height=70)
        living_room_click_region1.link_to_scene(computer_scene1)
        living_room_click_region2 = RectRegion(left= 550, top=390, width=60, height=70)
        living_room_click_region2.link_to_scene(phone_scene)
        living_room_scene.add_region(living_room_click_region2)
        living_room_scene.add_region(living_room_click_region1)
        living_room_scene.add_dir_link(Dir.RIGHT, dining_room_scene)
        phone_scene.add_dir_link(Dir.UP, living_room_scene)
        computer_scene1.add_dir_link(Dir.UP, living_room_scene)
        computer_scene1_click_region1 = RectRegion(left= 200, top=132, width=900, height=100)
        computer_scene1_click_region1.link_to_scene(computer_scene2)
        computer_scene1_click_region1.on_click(click_file)
        computer_scene1.add_region(computer_scene1_click_region1)
        computer_scene2.add_dir_link(Dir.UP, living_room_scene)
        dining_room_scene.add_dir_link(Dir.LEFT, living_room_scene)
        dining_room_scene_click_region1 = RectRegion(left= 1050, top=570, width=90, height=60)
        dining_room_scene_click_region1.link_to_scene(glass_scene)
        dining_room_scene.add_region(dining_room_scene_click_region1)
        dining_room_scene_click_region2 = RectRegion(left= 150, top=380, width=60, height=25)
        dining_room_scene_click_region2.on_click(click_key)
        dining_room_scene.add_region(dining_room_scene_click_region2)
        glass_scene.add_dir_link(Dir.UP, dining_room_scene)
        glass_scene_click_region1 = RectRegion(left= 0, top=0, width=1280, height=720)
        glass_scene_click_region1.link_to_scene(glass_removed_scene)
        glass_scene_click_region1.on_click(click_glass)
        glass_scene.add_region(glass_scene_click_region1)
        glass_removed_scene.add_dir_link(Dir.UP, dining_room_scene)
        bedroom_scene.add_dir_link(Dir.LEFT, dining_room_scene)
        bedroom_scene.add_dir_link(Dir.RIGHT, attic_scene)
        bedroom_scene_click_region1 = RectRegion(left= 10, top=610, width=140, height=90)
        bedroom_scene_click_region1.link_to_scene(journal_scene1)
        bedroom_scene.add_region(bedroom_scene_click_region1)
        journal_scene1.add_dir_link(Dir.UP, bedroom_scene)
        journal_scene1_click_region1 = RectRegion(left= 650, top=130, width=250, height=200)
        journal_scene1_click_region1.link_to_scene(journal_scene2)
        journal_scene1.add_region(journal_scene1_click_region1)
        journal_scene2.add_dir_link(Dir.UP, bedroom_scene)
        journal_scene2.add_dir_link(Dir.LEFT, journal_scene1)
        attic_scene.add_dir_link(Dir.LEFT, bedroom_scene)
        attic_scene_click_region1 = RectRegion(left= 1120, top=570, width=60, height=100)
        attic_scene_click_region1.link_to_scene(glove_scene)
        attic_scene.add_region(attic_scene_click_region1)
        attic_scene_click_region2 = RectRegion(left= 620, top=420, width=150, height=100)
        attic_scene_click_region2.link_to_scene(lockbox_scene)
        attic_scene.add_region(attic_scene_click_region2)
        lockbox_scene.add_dir_link(Dir.UP, attic_scene)
        lockbox_scene_click_region1 = RectRegion(left= 620, top=400, width=150, height=100)
        lockbox_scene_click_region1.on_click(click_box)
        lockbox_scene.add_region(lockbox_scene_click_region1)
        box_scene.add_dir_link(Dir.UP, attic_scene)
        glove_scene.add_dir_link(Dir.UP, attic_scene)
        glove_scene_click_region1 = RectRegion(left=830, top=290, width=200, height=150)
        glove_scene_click_region1.link_to_scene(glove_blood_scene)
        glove_scene.add_region(glove_scene_click_region1)
        glove_blood_scene.add_dir_link(Dir.UP, glove_scene)
        text_scene11.add_dir_link(Dir.LEFT, attic_scene)
        text_scene11.add_dir_link(Dir.RIGHT, accusation_scene1)
        accusation_scene1_click_region1 = RectRegion(left= 0, top=0, width=1280, height=720)
        accusation_scene1_click_region1.link_to_scene(accusation_scene2)
        accusation_scene1.add_region(accusation_scene1_click_region1)
        accusation_scene_click_region2 = RectRegion(left= 0, top=0, width=1280, height=720)
        accusation_scene_click_region2.link_to_scene(accusation_scene3)
        accusation_scene2.add_region(accusation_scene_click_region2)
        accusation_scene_click_region3 = RectRegion(left= 0, top=0, width=1280, height=720)
        accusation_scene_click_region3.link_to_scene(accusation_scene4)
        accusation_scene3.add_region(accusation_scene_click_region3)
        accusation_scene_click_region4 = RectRegion(left= 0, top=0, width = 1280, height=720)
        accusation_scene_click_region4.link_to_scene(accusation_scene5)
        accusation_scene4.add_region(accusation_scene_click_region4)
        accusation_scene_click_region5 = RectRegion(left= 0, top=0, width=1280, height=720)
        accusation_scene_click_region5.link_to_scene(accusation_scene6)
        accusation_scene5.add_region(accusation_scene_click_region5)
        accusation_scene_click_region6 = RectRegion(left= 0, top=0, width=1280, height=720)
        accusation_scene_click_region6.link_to_scene(accusation_scene7)
        accusation_scene6.add_region(accusation_scene_click_region6)
        accusation_scene7_click_region1 = RectRegion(left= 740, top=220, width=190, height=450)
        accusation_scene7_click_region1.link_to_scene(win_scene1)
        accusation_scene7.add_region(accusation_scene7_click_region1)
        accusation_scene_click_region2 = RectRegion(left= 200, top=200, width=200, height=500)
        accusation_scene_click_region2.link_to_scene(lose_scene)
        accusation_scene7.add_region(accusation_scene_click_region2)
        accusation_scene_click_region3 = RectRegion(left= 935, top=440, width=200, height=210)
        accusation_scene_click_region3.link_to_scene(lose_scene)
        accusation_scene7.add_region(accusation_scene_click_region3)
        accusation_scene_click_region4 = RectRegion(left= 600, top=220, width = 115, height=470)
        accusation_scene_click_region4.link_to_scene(lose_scene)
        accusation_scene7.add_region(accusation_scene_click_region4)
        accusation_scene_click_region5 = RectRegion(left= 410, top=200, width=150, height=470)
        accusation_scene_click_region5.link_to_scene(lose_scene)
        accusation_scene7.add_region(accusation_scene_click_region5)
        lose_scene_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        lose_scene_click_region1.link_to_scene(final_scene)
        lose_scene.add_region(lose_scene_click_region1)
        final_scene.add_dir_link(Dir.RIGHT, text_scene1)
        win_scene_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene_click_region1.link_to_scene(win_scene2)
        win_scene1.add_region(win_scene_click_region1)
        win_scene2_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene2_click_region1.link_to_scene(win_scene3)
        win_scene2.add_region(win_scene2_click_region1)
        win_scene3_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene3_click_region1.link_to_scene(win_scene4)
        win_scene3.add_region(win_scene3_click_region1)
        win_scene4_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene4_click_region1.link_to_scene(win_scene5)
        win_scene4.add_region(win_scene4_click_region1)
        win_scene5_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene5_click_region1.link_to_scene(win_scene6)
        win_scene5.add_region(win_scene5_click_region1)
        win_scene6_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene6_click_region1.link_to_scene(win_scene7)
        win_scene6.add_region(win_scene6_click_region1)
        win_scene7_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene7_click_region1.link_to_scene(win_scene8)
        win_scene7.add_region(win_scene7_click_region1)
        win_scene8_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene8_click_region1.link_to_scene(win_scene9)
        win_scene8.add_region(win_scene8_click_region1)
        win_scene9_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene9_click_region1.link_to_scene(win_scene10)
        win_scene9.add_region(win_scene9_click_region1)
        win_scene10_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene10_click_region1.link_to_scene(win_scene11)
        win_scene10.add_region(win_scene10_click_region1)
        win_scene11_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene11_click_region1.link_to_scene(win_scene12)
        win_scene11.add_region(win_scene11_click_region1)
        win_scene12_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene12_click_region1.link_to_scene(win_scene13)
        win_scene12.add_region(win_scene12_click_region1)
        win_scene13_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene13_click_region1.link_to_scene(win_scene14)
        win_scene13.add_region(win_scene13_click_region1)
        win_scene14_click_region1 = RectRegion(left=0, top=0, width=1280, height=720)
        win_scene14_click_region1.link_to_scene(final_scene)
        win_scene14.add_region(win_scene14_click_region1)
        

        self.set_start_scene(text_scene1)
init()
while True:
    # run the game until quit or restart
    run_result = ExampleGame().run()


    # if run_result is False, the game should quit. otherwise, we loop and restart it
    if not run_result:
        break
quit()
